"""add user privacy and follow tables

Revision ID: 22f2498b8aad
Revises: d19478d3a58c
Create Date: 2026-09-15 09:57:17.941294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f2498b8aad'
down_revision: Union[str, Sequence[str], None] = 'd19478d3a58c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    media_type_enum =sa.Enum("tv","movie", name="mediatype")
    media_type_enum.create(op.get_bind(),checkfirst=True)

    op.create_table('follow_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', name='requeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id')
    )
    op.create_table('follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'following_id')
    )
    op.alter_column('media', 'media_type',
               existing_type=sa.VARCHAR(),
               type_=media_type_enum,
               existing_nullable=False,
    postgresql_using="media_type::mediatype",)
    op.add_column('users', sa.Column('is_private', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    media_type_enum =sa.Enum("tv","movie", name="mediatype")
    op.drop_column('users', 'is_private')
    op.alter_column('media', 'media_type',
               existing_type=sa.Enum('tv', 'movie', name='mediatype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_table('follows')
    op.drop_table('follow_requests')
    media_type_enum.drop(op.get_bind(), checkfirst=True)
    # request_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
