"""Add cascading

Revision ID: 31c512f2ae50
Revises: 22f2498b8aad
Create Date: 2026-09-18 23:39:17.578302

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31c512f2ae50"
down_revision: Union[str, Sequence[str], None] = "22f2498b8aad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("follow_requests_follower_id_fkey"), "follow_requests", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("follow_requests_following_id_fkey"), "follow_requests", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "follow_requests", "users", ["follower_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "follow_requests", "users", ["following_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("follows_following_id_fkey"), "follows", type_="foreignkey")
    op.drop_constraint(op.f("follows_follower_id_fkey"), "follows", type_="foreignkey")
    op.create_foreign_key(
        None, "follows", "users", ["follower_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None, "follows", "users", ["following_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("reviews_user_id_fkey"), "reviews", type_="foreignkey")
    op.create_foreign_key(
        None, "reviews", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("watchlist_user_id_fkey"), "watchlist", type_="foreignkey")
    op.create_foreign_key(
        None, "watchlist", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "watchlist", type_="foreignkey")
    op.create_foreign_key(
        op.f("watchlist_user_id_fkey"), "watchlist", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "reviews", type_="foreignkey")
    op.create_foreign_key(
        op.f("reviews_user_id_fkey"), "reviews", "users", ["user_id"], ["id"]
    )
    op.drop_constraint(None, "follows", type_="foreignkey")
    op.drop_constraint(None, "follows", type_="foreignkey")
    op.create_foreign_key(
        op.f("follows_follower_id_fkey"), "follows", "users", ["follower_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("follows_following_id_fkey"), "follows", "users", ["following_id"], ["id"]
    )
    op.drop_constraint(None, "follow_requests", type_="foreignkey")
    op.drop_constraint(None, "follow_requests", type_="foreignkey")
    op.create_foreign_key(
        op.f("follow_requests_following_id_fkey"),
        "follow_requests",
        "users",
        ["following_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("follow_requests_follower_id_fkey"),
        "follow_requests",
        "users",
        ["follower_id"],
        ["id"],
    )
    # ### end Alembic commands ###
