"""add status to watchlist

Revision ID: 513756f80505
Revises: 51241f14ae99
Create Date: 2026-09-21 22:41:01.528047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '513756f80505'
down_revision: Union[str, Sequence[str], None] = '51241f14ae99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    watchlist_status_enum =sa.Enum('unwatched', 'watching', 'watched', name="watchliststatus")
    watchlist_status_enum.create(op.get_bind(),checkfirst=True)

    op.add_column('watchlist', sa.Column('status', sa.Enum('unwatched',name='watchliststatus') , nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    watchlist_status_enum =sa.Enum('unwatched', 'watching', 'watched', name="watchliststatus")
    op.drop_column('watchlist', 'status')
    watchlist_status_enum.drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
