"""Add media_activities table and poster_path column to media

Revision ID: c96ad4246476
Revises: ad03a20ba8ea
Create Date: 2026-10-02 08:05:36.593292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c96ad4246476"
down_revision: Union[str, Sequence[str], None] = "ad03a20ba8ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "media_activities",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.Column(
            "activity",
            sa.Enum("watched", "loved", "liked", "disliked", name="mediaactivitytype"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["media_id"], ["media.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "media_id", "activity"),
    )
    op.add_column("media", sa.Column("poster_path", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media", "poster_path")
    op.drop_table("media_activities")
    # ### end Alembic commands ###
