"""Add verification fields and refresh token support

Revision ID: efba007478f9
Revises: c96ad4246476
Create Date: 2026-10-05 09:18:25.212680

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "efba007478f9"
down_revision: Union[str, Sequence[str], None] = "c96ad4246476"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("verification_code", sa.String(), nullable=True))
    op.add_column(
        "users",
        sa.Column("verification_expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("users", sa.Column("refresh_token", sa.String(), nullable=True))
    op.alter_column("users", "is_verified", existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "is_verified", existing_type=sa.BOOLEAN(), nullable=True)
    op.drop_column("users", "refresh_token")
    op.drop_column("users", "verification_expires_at")
    op.drop_column("users", "verification_code")
    # ### end Alembic commands ###
