"""Rename release_date to premiere_date

Revision ID: ff6a217d25ca
Revises: 1cfc75dbd60e
Create Date: 2026-09-13 12:37:52.319203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff6a217d25ca'
down_revision: Union[str, Sequence[str], None] = '1cfc75dbd60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('premiere_date', sa.Date(), nullable=True))
    op.drop_column('media', 'release_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('release_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('media', 'premiere_date')
    # ### end Alembic commands ###
